### ISSUE TITLE
Data from French overseas departments

### ISSUE THREAD

**Issue by st2048** [akarlinsky/world_mortality#12]
Hello,

I hope you are well.

My understanding from the [STMF metadata file](mortality.org/Public/STMF_DOC/STMFmetadata.pdf) is that data from France covers metropolitan France only, i.e., excluding the overseas departments.

In case you are interested in adding data from the French overseas departments as separate dependencies, I wanted to point out that data from all five overseas departments (Guadeloupe, Martinique, Guyane, La Réunion and Mayotte) is available from Eurostat (see the ['Deaths by week, sex, 20-year age group and NUTS 2 region'](https://ec.europa.eu/eurostat/databrowser/view/DEMO_R_MWK2_TS__custom_1077846/default/table?lang=en) dataset).

Once again, thank you very much for all your work.

**Comment by dkobak** [comment]
That's a really cool find.

1) When grabbing data from Eurostat to merge with STMF, we should exclude overseas departments because that's what STMF does.

2) We could include all five overseas departments separately into our data if the Eurostat provides enough data for them. How are they treated in the WHO/JHU dashboards? Can we get official Covid deaths from there?

**Comment by akarlinsky** [comment]
Thank you @st2048! 
I wanted to add Martinique and other French overseas departments for a while, but was only able to find information up to 2019 [here](https://www.insee.fr/fr/statistiques/1893253). We will add this in one of the next updates. 

We try to credit all of those who have helped us obtain and find data. 
If you would like to be credited with your name you can email me or write here.
