### ISSUE TITLE
Data for Australia Looks wrong

### ISSUE THREAD

**Issue by billkonstantinidis** [akarlinsky/world_mortality#17]
Looks wrong - Government reported total deaths in 2019 states as 169,301 (see link)
https://www.abs.gov.au/statistics/people/population/deaths-australia/latest-release

Deaths in dataset shows 143,808

**Comment by akarlinsky** [comment]
Similar to ABS, our measure for mortality in Australia 2020-2021 is "Doctor Certified Deaths", since "All Deaths" are not yet available: https://www.abs.gov.au/statistics/health/causes-death/provisional-mortality-statistics/latest-release

This is clearly stated in our README: https://github.com/akarlinsky/world_mortality#human-mortality-database-short-term-mortality-flucations
![image](https://user-images.githubusercontent.com/48435065/132216790-8448110d-764f-4255-9255-3695239e9732.png)
