### ISSUE TITLE
Additional source for Brazilian mortality data

### ISSUE THREAD

**Issue by dyokomizo** [akarlinsky/world_mortality#2]
In Brazil data from the "Brazilian Population Registry" may be incomplete for several reasons (e.g. quality of data, system bug, revisions like this one ["546,490 records of different years and months have disappeared from the system"](https://www1.folha.uol.com.br/equilibrioesaude/2020/05/meio-milhao-de-mortes-somem-de-sistema-usado-para-monitorar-covid-19.shtml)).

The Ministry of Health offers data from 1996 to 2019 in [this site](http://tabnet.datasus.gov.br/cgi/deftohtm.exe?sim/cnv/obt10uf.def). It has options to filter and aggregate the data in various ways.

**Comment by akarlinsky** [comment]
Thank you - this is very helpful! 
WM will take 2015-2019 data from MOH in the next update. 

Do you know if and when MOH planes on releasing 2020 data?

**Comment by dyokomizo** [comment]
> Do you know if and when MOH planes on releasing 2020 data?

I have no clue, IIRC in the previous years it took 2-3 months, but with the pandemic I'll be happy if it's even released before July this year.

**Comment by akarlinsky** [comment]
We have decided for now to stick with Brazil's Population Registry Data, and added this note to the README:

Note: Brazilian Population Registry seems to be downward biased compared to 2015-2019 data from Brazil's Ministry of Health (http://tabnet.datasus.gov.br/cgi/deftohtm.exe?sim/cnv/obt10uf.def) by about 7 to 10%. For now we chose to stay with the Population Registry Data in order to best insure consistency with 2020-2021 data.

**Comment by akarlinsky** [comment]
After consulting with [Marcelo Oliveira](https://github.com/capyvara) and [Otavio Ranzani](https://github.com/oranzani/), we have decided to change our source and method for Brazilian all-cause mortality data. 
See README for details.
